---
# Defines deployment design and assigns role to server groups

- hosts:
  - mons
  - osds
  - mdss
  - rgws
  - clients # Kernel RBD does NOT support signatures for Kernels < 3.18! Make sure to set cephx_require_signatures: false
  sudo: True
  roles:
  - { role: ceph-common, when: not docker }

- hosts: mons
  sudo: True
  roles:
  - ceph-mon
  - { role: ceph-restapi, when: restapi }

- hosts: osds
  sudo: True
  roles:
  - ceph-osd

- hosts: mdss
  sudo: True
  roles:
  - ceph-mds

- hosts: rgws
  sudo: True
  roles:
  - ceph-radosgw
