---
- include: pre_requisite.yml

- name: check if Ceph REST API is already started
  shell: "ps aux|grep [c]eph-rest-api"
  register: restapi_status
  ignore_errors: True

- name: start Ceph REST API
  shell: "nohup ceph-rest-api &"
  when: restapi_status.rc != 0
  changed_when: False
