---
- name: install dependencies
  yum: >
    name={{ item }}
    state=present
  with_items:
    - python-pycurl
    - ntp
    - hdparm
    - yum-plugin-priorities.noarch
    - epel-release

- name: install the Ceph stable repository key
  rpm_key: >
    key={{ ceph_stable_key }}
    state=present
  when: ceph_stable

- name: install the Ceph development repository key
  rpm_key: >
    key={{ ceph_dev_key }}
    state=present
  when: ceph_dev

- name: install Inktank Ceph Enterprise repository key
  rpm_key: >
    key={{ ceph_stable_ice_temp_path }}/release.asc
    state=present
  when: ceph_stable_ice

- name: add Ceph stable repository
  yum: name=http://ceph.com/rpm-{{ ceph_stable_release }}/{{ ceph_stable_redhat_distro }}/noarch/ceph-release-1-0.{{ ceph_stable_redhat_distro|replace('rhel', 'el') }}.noarch.rpm
  register: repo_result
  when: ceph_stable
  failed_when: repo_result.rc > 1
  changed_when: repo_result.rc == 0

- name: add Ceph development repository
  yum: name=http://gitbuilder.ceph.com/ceph-rpm-{{ ceph_dev_redhat_distro }}-x86_64-basic/ref/{{ ceph_dev_branch }}/noarch/ceph-release-1-0.{{ ceph_stable_redhat_distro }}.noarch.rpm
  register: repo_result
  when: ceph_dev
  failed_when: repo_result.rc > 1
  changed_when: repo_result.rc == 0

- name: add Inktank Ceph Enterprise repository
  template: >
    src=redhat_ice_repo.j2
    dest=/etc/yum.repos.d/ice.repo
    owner=root
    group=root
    mode=0644
  when: ceph_stable_ice

- name: install Ceph
  yum: >
    name=ceph
    state=latest

- name: install Inktank Ceph Enterprise RBD Kernel modules
  yum: >
    name={{ item }}
  with_items:
    - "{{ ceph_stable_ice_temp_path }}/kmod-libceph-{{ ceph_stable_ice_kmod }}.rpm"
    - "{{ ceph_stable_ice_temp_path }}/kmod-rbd-{{ ceph_stable_ice_kmod }}.rpm"
  when: ceph_stable_ice
