---
- name: update apt cache
  apt: update-cache=yes

- name: restart ceph mons
  command: service ceph restart mon
  when: socket.rc == 0 and 'mons' in group_names

- name: restart ceph osds
  command: service ceph restart osd
  when: socket.rc == 0 and 'osds' in group_names

- name: restart ceph osds on ubuntu
  command: restart ceph-osd-all
  when: socket.rc == 0 and ansible_distribution == 'Ubuntu' and 'osds' in group_names

- name: restart ceph mdss
  command: service ceph restart mds
  when: socket.rc == 0 and 'mdss' in group_names

- name: restart ceph rgws
  command: /etc/init.d/radosgw restart
  when: socket.rc == 0 and 'rgws' in group_names
