---
## SCENARIO 3: N JOURNAL DEVICES FOR N OSDS

- include: zap_devices.yml
- include: check_devices.yml

# NOTE (leseb): the prepare process must be parallelized somehow...
# if you have 64 disks with 4TB each, this will take a while
# since Ansible will sequential process the loop

# NOTE (alahouze): if the device is a partition, the parted command below has
# failed, this is why we check if the device is a partition too.
- name: prepare OSD disk(s)
  command: "ceph-disk prepare {{ item.2 }} {{ item.3 }}"
  when: (item.0.rc != 0 or item.1.rc != 0) and raw_multi_journal
  ignore_errors: True
  with_together:
    - parted.results
    - ispartition.results
    - devices
    - raw_journal_devices
  changed_when: False

- include: activate_osds.yml
