---
- name: create filesystem pools
  command: ceph osd pool create {{ item }} {{ pool_default_pg_num }}
  with_items:
    - cephfs_data
    - cephfs_metadata
  changed_when: False

- name: create Ceph Filesystem
  command: ceph fs new {{ cephfs }} {{ cephfs_metadata }} {{ cephfs_data }}
  changed_when: False
