---
- name: create OpenStack pool
  command: rados mkpool {{ item }}
  with_items:
    - "{{ openstack_glance_pool }}"
    - "{{ openstack_cinder_pool }}"
    - "{{ openstack_nova_pool }}"
    - "{{ openstack_cinder_backup_pool }}"
  ignore_errors: True
  changed_when: False

- name: create OpenStack keys
  command: >
    ceph auth get-or-create {{ item.name }} {{ item.value }} -o /etc/ceph/ceph.{{ item.name }}.keyring
    creates=/etc/ceph/ceph.{{ item.name }}.keyring
  with_items: openstack_keys
  changed_when: False
