---
- name: collect all the pool
  command: rados lspools
  register: ceph_pools

- name: secure the cluster
  command: ceph osd pool set {{ item[0] }} {{ item[1] }} true
  with_nested:
    - ceph_pools.stdout_lines
    - secure_cluster_flags
