---
- name: fetch Ceph config and keys
  copy: >
    src=fetch/docker_mon_files/{{ item }}
    dest=/etc/ceph/
    owner=root
    group=root
    mode=600
  with_items:
    - /etc/ceph/ceph.client.admin.keyring
    - /etc/ceph/ceph.conf
    - /etc/ceph/monmap
    - /etc/ceph/ceph.mon.keyring

- name: run the Ceph Medata docker image
  docker: >
    image="{{ ceph_mds_docker_username }}/{{ ceph_mds_docker_imagename }}"
    name=ceph-mds-{{ ansible_hostname }}
    net=host
    state=running
    env="MDS_NAME=ceph-mds-{{ ansible_hostname }}, MDS_CIVETWEB_PORT={{ ceph_mds_civetweb_port }}"
    volumes="/var/lib/ceph:/var/lib/ceph,/etc/ceph:/etc/ceph"

- name: ensure ceph_mds service is running
  docker: >
    image="{{ ceph_mds_docker_username }}/{{ ceph_mds_docker_imagename }}"
    name="ceph-{{ ansible_hostname }}"
    detach=yes
    state=running
